(function(){
  const recordForm=document.getElementById('record-form'),projectForm=document.getElementById('project-form');
  function refreshAll(){Object.values(Pages).forEach(p=>p.refresh())}
  function options(selected){return Store.data.projects.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${p.name}</option>`).join('')}
  function liveEfficiency(){const p=Store.project(Number(recordForm.pid.value)),minutes=Number(recordForm.minutes.value),actual=Number(recordForm.actual.value),standard=p?minutes*p.rate:0;document.getElementById('live-efficiency').textContent=standard>0?`${Math.round(actual/standard*100)}%`:'—'}
  function openRecord(id){const record=Store.data.records.find(r=>r.id===id);document.getElementById('record-sheet-title').textContent=record?'编辑记录':'记录项目';recordForm.id.value=record?.id||'';recordForm.pid.innerHTML=options(record?.pid||Store.data.projects[0]?.id);recordForm.date.value=record?.date||Store.today();recordForm.start.value=record?.start||new Date().toTimeString().slice(0,5);recordForm.minutes.value=record?.minutes||60;recordForm.actual.value=record?.actual??'';document.getElementById('delete-record').hidden=!record;liveEfficiency();UI.showSheet('record-sheet');setTimeout(()=>recordForm.actual.focus(),310)}
  function updateRule(){document.getElementById('rule-rate').textContent=projectForm.rate.value||'1';document.getElementById('rule-unit').textContent=projectForm.unit.value||'个'}
  function openProject(id){const p=Store.project(id);document.getElementById('project-sheet-title').textContent=p?'编辑项目':'新建项目';projectForm.id.value=p?.id||'';projectForm.name.value=p?.name||'';projectForm.unit.value=p?.unit||'个';projectForm.rate.value=p?.rate||1;projectForm.color.value=p?.color||'#1677ff';document.getElementById('delete-project').hidden=!p;updateRule();UI.showSheet('project-sheet');setTimeout(()=>projectForm.name.focus(),310)}
  recordForm.addEventListener('input',liveEfficiency);recordForm.addEventListener('submit',e=>{e.preventDefault();Store.saveRecord({id:Number(recordForm.id.value)||undefined,pid:Number(recordForm.pid.value),date:recordForm.date.value,start:recordForm.start.value,minutes:Number(recordForm.minutes.value),actual:Number(recordForm.actual.value)});UI.closeSheets();refreshAll();UI.toast(recordForm.id.value?'记录已更新':'记录已保存')});
  document.getElementById('delete-record').onclick=()=>{const id=Number(recordForm.id.value);if(id&&confirm('删除这条工作记录？')){Store.deleteRecord(id);UI.closeSheets();refreshAll();UI.toast('记录已删除')}};
  projectForm.addEventListener('input',updateRule);projectForm.addEventListener('submit',e=>{e.preventDefault();Store.saveProject({id:Number(projectForm.id.value)||undefined,name:projectForm.name.value.trim(),unit:projectForm.unit.value.trim(),rate:Number(projectForm.rate.value),color:projectForm.color.value});UI.closeSheets();refreshAll();UI.toast(projectForm.id.value?'项目已更新':'项目已创建')});
  document.getElementById('delete-project').onclick=()=>{const id=Number(projectForm.id.value);if(id&&confirm('删除项目及其相关工作记录？')){Store.deleteProject(id);UI.closeSheets();refreshAll();UI.toast('项目已删除')}};
  window.App={openRecord,openProject,refreshAll};Router.init();refreshAll();
})();
